version: '3'
services:
    mysql:
        image: mysql:8.0.20
        restart: always
        volumes:
            - ./fixtures:/tmp
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
        security_opt:
            - apparmor:unconfined
    api:
        build: .
        restart: always
        depends_on:
            - mysql
        ports:
            - "8000:8000"