version: '3'
services:
    postgres:
        image: postgres:11.9
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./fixtures:/tmp
    api:
        image: davidtnfsh/dt42_piggy_api:latest
        restart: always
        environment:
            - LINE_TOKEN=xxx
            - GMAIL_TOKEN=xxx
            - EMAIL_OF_SENDER=xxx
            - EMAIL_OF_RECEIVER=xxx
        depends_on:
            - postgres
        ports:
            - "8000:8000"