version: '3'
services:
    mysql:
        image: mysql:8.0.20
        volumes:
            - ./fixtures:/tmp
        environment:
            - MYSQL_ROOT_PASSWORD=mysql
    api:
        build: .
        restart: always
        depends_on:
            - mysql
        ports:
            - "8000:8000"