version: '3'
services:
    postgres:
        image: postgres:11.9
        restart: always
        environment:
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./fixtures:/tmp
    api:
        image: davidtnfsh/dt42_piggy_api:cache
        restart: always
        environment:
            - LOCATION=dev
        depends_on:
            - postgres
        ports:
            - "8000:8000"